### ISSUE TITLE
Factory reset

### ISSUE THREAD

**Issue by francescom1973** [m5stack/Core2-for-AWS-IoT-EduKit#11]
How do I factory reset the unit ? 
I gave the wrong password during setup and now I am told to factory reset. 
I (84610) wifi:state: init -> auth (b0)
I (84610) wifi:state: auth -> assoc (0)
I (84620) wifi:state: assoc -> run (10)
I (87640) wifi:state: run -> init (2a0)
I (87640) wifi:new:<7,0>, old:<7,2>, ap:<255,255>, sta:<7,2>, prof:1
I (87640) wifi:new:<7,0>, old:<7,0>, ap:<255,255>, sta:<7,2>, prof:1
␛[0;32mI (87640) app_wifi: Disconnected. Connecting to the AP again...␛[0m
␛[0;32mI (89700) app_wifi: Disconnected. Connecting to the AP again...␛[0m
I (89820) wifi:new:<7,2>, old:<7,0>, ap:<255,255>, sta:<7,2>, prof:1
I (89830) wifi:state: init -> auth (b0)
I (90830) wifi:state: auth -> init (200)
I (90830) wifi:new:<7,0>, old:<7,2>, ap:<255,255>, sta:<7,2>, prof:1
␛[0;32mI (90830) app_wifi: Disconnected. Connecting to the AP again...␛[0m
␛[0;32mI (92890) app_wifi: Disconnected. Connecting to the AP again...␛[0m
I (93010) wifi:new:<7,2>, old:<7,0>, ap:<255,255>, sta:<7,2>, prof:1

**Comment by rashedtalukder** [comment]
So here's the dilemma... the more steps and instructions I include, the more that humans tend to skim and skip. If you look at the section you were in about setting the Wi-Fi credentials, there is a "Info" block at the bottom that gives the solution to your very problem: https://edukit.workshop.aws/en/getting-started/run-rainmaker.html#claiming-and-provisioning-the-device
