### ISSUE TITLE
Lots of missing dependencies

### ISSUE THREAD

**Issue by scarolan** [m5stack/Core2-for-AWS-IoT-EduKit#18]
Following the instructions to build the device firmware, it seems there are a ton of missing libraries.  For example:

src\app_driver.c:11:24: fatal error: iot_button.h: No such file or directory

src\fan.h:26:29: fatal error: esp_rmaker_core.h: No such file or directory

**Comment by rashedtalukder** [comment]
Closing. This is related to: https://github.com/m5stack/Core2-for-AWS-IoT-EduKit/issues/19
