### ISSUE TITLE
MakeFile needs to be moved to subfolder

### ISSUE THREAD

**Issue by bgilreath** [m5stack/Core2-for-AWS-IoT-EduKit#2]
Build will fail following Getting-Started instructions Build, Upload and Monitor.

**Comment by rashedtalukder** [comment]
Shouldn't result in a fail in PlatformIO, but the Makefile contents are incorrect and need to be updated. Will modify, test, and update today.

**Comment by rashedtalukder** [comment]
Fixed: https://github.com/m5stack/Core2-for-AWS-IoT-EduKit/blob/63d86d096d6f8223bfb728ec98fe9947c29b7b14/Getting-Started/Makefile
