### ISSUE TITLE
pyasn_modules and jose module required by registration helper

### ISSUE THREAD

**Issue by scarolan** [m5stack/Core2-for-AWS-IoT-EduKit#22]
The fix on Windows 10:

pip install pyasn1_modules jose

**Comment by rashedtalukder** [comment]
This is part of the requirements.txt file in the registration helper script. If you ran pip install -r requirements, this should’ve been satisfied.

**Comment by rashedtalukder** [comment]
The versions of those also cannot be the latest. Some of the APIs had changed and will not work correctly. Please see the Core2-for-AWS-IoT-EduKit\Blinky-Hello-World\utilities\AWS_IoT_registration_helper\requirements.txt file for the correct necessary versions of dependencies that work with the other underlying libraries.
