### ISSUE TITLE
Blinky-Hello-World> Connnecting to AWS IoT Core > Not seeing AWS IoT EduKit Configuration in KConfig

### ISSUE THREAD

**Issue by kevkearney** [m5stack/Core2-for-AWS-IoT-EduKit#25]
![Screenshot from 2020-12-30 11-57-25](https://user-images.githubusercontent.com/7997022/103368775-6a114a80-4a96-11eb-8107-3aa93e18cd3c.png)

**Comment by rashedtalukder** [comment]
Hi, please verify you are in the `/Core2-for-AWS-IoT-EduKit/Blinky-Hello-World` directory.

**Comment by kevkearney** [comment]
I am.

**Comment by kevkearney** [comment]
I was able to set the AWS Iot Endpoint Hostname, but I can't find the next part, for SSID and wifi key.

**Comment by kevkearney** [comment]
I also don't see it in the Kconfig file in the project.

**Comment by kevkearney** [comment]
Ah wait, I see it in kconfig.projbuild. Let me see if I can get it to build.

**Comment by kevkearney** [comment]
Sorry, let me be more clear:
I see the kconfig options in the main folder, in kconfig.projbuild, but for some reason when I run the `idf.py menuconfig` command, they aren't included in the menu.

**Comment by rashedtalukder** [comment]
The idf.py menuconfig command reads the kconfig files from each of the linked dependencies. In this case:
`/Core2-for-AWS-IoT-EduKit/Blinky-Hello-World/main/Kconfig.projbuild`

For some reason it's not reading it for you. Can you list your OS and version as well? Also run a `idf.py fullclean` to erase any strange build configurations. Even if you modify your kconfig.projbuild to have your Wi-Fi credentials, when you begin the build process it with generate a **sdkconfig** file, which contains all of your application configurations and is what the ESP Tools then parse for your linker and compile options.

**Comment by kevkearney** [comment]
Sure, let me provide more info:

Ubuntu 20.04 on a clean install specific for the purposes of playing with the m5stack

Here is a pastebin of my output:
https://pastebin.com/DkCB55c8

**Comment by rashedtalukder** [comment]
I am setting up a fresh test environment to see if I can duplicate, just that it takes a while :)

**Comment by kevkearney** [comment]
No problem, I'm trying to figure it out on my side as well.
Let me know where I can be of assistance.

**Comment by rashedtalukder** [comment]
Resolved in https://github.com/m5stack/Core2-for-AWS-IoT-EduKit/commit/aa99a24f8708c9a65abf1066ec14460bba56a915. Filename case was incorrect (needs capital **K**). Menuconfig never threw any errors so we didn't catch it. Espressif's documentation also has the wrong file name in their docs (https://github.com/m5stack/Core2-for-AWS-IoT-EduKit/commit/aa99a24f8708c9a65abf1066ec14460bba56a915). Thanks for filing this issue!

**Comment by kevkearney** [comment]
Yup, it worked. Thanks
