### ISSUE TITLE
Hello World - Blinking the LEDs fails

### ISSUE THREAD

**Issue by scarolan** [m5stack/Core2-for-AWS-IoT-EduKit#28]
I have my device successfully connecting to AWS IoT:

```
I (10500) aws_iot: Attempting to use device certificate from ATECC608
I (16800) Blinky: Successfully connected to AWS IoT Core!
I (16800) Blinky: Subscribing...
I (17040) Blinky: Subscribed to topic: 012333b76cac4c3701/#
I (17040) Blinky: 
I (17040) Blinky: **************************************
I (17040) Blinky: Client Id - 012333b76cac4c3701
I (17050) Blinky: **************************************
```

I subscribed to the # topic per the instructions, but when I publish nothing happens on the device:

![blink](https://user-images.githubusercontent.com/403332/103379578-b31fc980-4aab-11eb-8392-2a9d3a59aeea.png)

**Comment by scarolan** [comment]
Never mind, i was in the wrong region!

**Comment by rashedtalukder** [comment]
Thank you for reporting, Sean. I've updated all links that point to the console to go to us-west-2 so anyone in the future doesn't encounter the same issue.

**Comment by muriloplinio** [comment]
I have the same problem and this post helps me!! Thank you!

wrong region!

Now it is working!
