### ISSUE TITLE
Getting started, need to release com port before erasing

### ISSUE THREAD

**Issue by bentterp** [m5stack/Core2-for-AWS-IoT-EduKit#34]
Hi

I think there's a step missing in the Getting Started, after upload and monitor the com port remains in use by the monitoring loop, so I get Permission Denied when trying to erase flash. I need to terminate the loop with CTRL-C, then I can do the erase - but it doesn't reset the device, I need to powercycle it before getting the empty state.

And maybe you could add the explanation that a black screen with a ticking sound doesn't mean you've broken anything but simply that there was nothing to boot from which is expected at this point

**Comment by rashedtalukder** [comment]
Added to: https://edukit.workshop.aws/en/getting-started/run-rainmaker.html#erasing-the-firmware-with-platformio
