### ISSUE TITLE
Blinky Hello World, install awscli first then miniconda

### ISSUE THREAD

**Issue by bentterp** [m5stack/Core2-for-AWS-IoT-EduKit#35]
If you open the anaconda prompt before installing the awscli on Windows, then anaconda doesn't see the updated path and can't find the aws tool.

So, better to install the CLI first and then the miniconda

**Comment by rashedtalukder** [comment]
Updated the module based on your recommendation. Thank you @bentterp!

https://edukit.workshop.aws/en/blinky-hello-world/prerequisites.html#installing-and-configuring-the-aws-cli-version-2
