### ISSUE TITLE
Documentation Typo on Mac Serial Port

### ISSUE THREAD

**Issue by deeheber** [m5stack/Core2-for-AWS-IoT-EduKit#38]
I clicked "bug report" and it led me to here, so I hope this is the right place to report this type of thing.

In the docs [here](https://edukit.workshop.aws/en/blinky-hello-world/device-provisioning.html#identifying-the-serial-port-on-host-machine) it says `For macOS, the device is typically on /dev/cu.SLABUSBtoUART`

Noticed the port is missing a `_`. The sentence should read `For macOS, the device is typically on /dev/cu.SLAB_USBtoUART`

**Comment by rashedtalukder** [comment]
Perfect! Thank you for filing that. It has been fixed.
