### ISSUE TITLE
Docs unclear to get started

### ISSUE THREAD

**Issue by gherlein** [m5stack/Core2-for-AWS-IoT-EduKit#4]
https://edukit.workshop.aws/en/ is where the barcode sends you, but it is NOT clear that the first thing you need to do is flash the device.  The instructions there say: 

"Once you receive the hardware kit, access the getting started tutorial and follow the steps to install the Espressif Rainmaker Mobile App on your phone. The Espressif Rainmaker Mobile App will allow you to control the AWS IoT EduKit reference hardware and connect to AWS IoT. Next, you can select from a list of free projects available on AWS IoT EduKit’s website. Start with building a basic connected home application and progress over time to running a machine learning model with Amazon SageMaker Autopilot or building a Voice Assisted Smart Home application with Alexa Voice Service Integration for AWS IoT (AFI)."

In reality, you need to follow the directions here:  https://edukit.workshop.aws/en/getting-started/prerequisites.html and flash the unit first.  The Rainmaker app cannot be used until that step is done.  The firmware in the unit just displays the barcode (according to M5Stack support).

**Comment by rashedtalukder** [comment]
Updated for accuracy based on your feedback:
https://edukit.workshop.aws/en/
