### ISSUE TITLE
Finding the serial port on MacOS Big Sur

### ISSUE THREAD

**Issue by guysqr** [m5stack/Core2-for-AWS-IoT-EduKit#41]
On Big Sur the device address was not as indicated in the docs. I needed to use the Pio CLI tool

`pio devices list`

to find the correct device. In my case:

```
% pio device list
/dev/cu.Bluetooth-Incoming-Port
-------------------------------
Hardware ID: n/a
Description: n/a

/dev/cu.usbserial-0202E71A
--------------------------
Hardware ID: USB VID:PID=10C4:EA60 SER=0202E71A LOCATION=20-3
Description: CP2104 USB to UART Bridge Controller - CP2104 USB to UART Bridge Controller
```

**Comment by rashedtalukder** [comment]
Interesting. Thank you for posting @guysqr. I'm going to close this since it's not an issue but I will be updating our documentation in the near future to incorporate this step.
