### ISSUE TITLE
USB Connection Name Different on Mac/BigSur

### ISSUE THREAD

**Issue by brianivie** [m5stack/Core2-for-AWS-IoT-EduKit#43]
When I connected the device to my Mac via USB cable the port name does show up for "ls -l /dev/cu.S*" command:
![image](https://user-images.githubusercontent.com/1048358/108608443-234c1c80-7384-11eb-996c-bb4770bfee9d.png)

Here is the list with the device disconnected:
![image](https://user-images.githubusercontent.com/1048358/108608478-55f61500-7384-11eb-9f5e-5ccf08ca006b.png)

And here is the list with the device connected:
![image](https://user-images.githubusercontent.com/1048358/108608488-6ad2a880-7384-11eb-812c-fea47943d303.png)

So "ls -l /dev/cu.usb*" would be a better command to get the port for a Mac running BigSur:
![image](https://user-images.githubusercontent.com/1048358/108608520-a3728200-7384-11eb-973e-aeb89d970103.png)

**Comment by rashedtalukder** [comment]
Noted. This is something that seems to be new as of recently. I will update the content to reflect this shortly. Thank you for updating.
