### ISSUE TITLE
Certificate Issue?

### ISSUE THREAD

**Issue by JCrossman** [m5stack/Core2-for-AWS-IoT-EduKit#46]
Anyone else have an issue connecting to IoT Core? I'm getting the following error:
I (3756) aws_iot: Attempting to use device certificate from ATECC608
E (7706) aws_iot: failed! mbedtls_ssl_handshake returned -0x4c80
E (7706) Blinky: Error(-4) connecting to xxxxxxxxxxxxxxxxx-ats.iot.us-west-2.amazonaws.com:8883

The certificate generation step using registration_helper.py finished without issue. And I have confirmed the endpoint.

**Comment by rashedtalukder** [comment]
Duplicate to https://github.com/aws-samples/aws-iot-edukit-tutorials/discussions/14
