### ISSUE TITLE
macOS setup instructions reference linux commands

### ISSUE THREAD

**Issue by joshka** [m5stack/Core2-for-AWS-IoT-EduKit#49]
On https://edukit.workshop.aws/en/getting-started/prerequisites/macos.html
```
sudo apt install build-essential python3-pip curl git cmake
```
While macOS may have an `apt` command, this is more likely the java annotation processing tool not the packaging tool in Debian / Ubuntu.

**Comment by joshka** [comment]
Semi related - the links to Mac / Win on https://edukit.workshop.aws/en/getting-started/prerequisites.html return Access Denied results.

**Comment by rashedtalukder** [comment]
Fixed. Thank you for reporting.
