### ISSUE TITLE
Docs need to be a lot more clear on the QR Codes

### ISSUE THREAD

**Issue by gherlein** [m5stack/Core2-for-AWS-IoT-EduKit#5]
The unit ships with a QR code on screen that takes you to https://edukit.workshop.aws/en/ - but then following the instructions you build and then need to scan the barcode that is on your computer screen to claim the device.

This should be a LOT more clear in the instructions up front to make it simpler for customers to understand.  If you scan the barcode that ships on the device with Rainmaker you just get an error.

**Comment by rashedtalukder** [comment]
Updated to make it clearer with an image:
http://localhost:1313/en_uk/getting-started/run-rainmaker.html#claiming-and-provisioning-the-device
