### ISSUE TITLE
CONNECTING TO AWS IOT CORE > Configuring the ESP32 Firmware

### ISSUE THREAD

**Issue by xian042** [m5stack/Core2-for-AWS-IoT-EduKit#64]
the instructions say that after entering the command

_pio run --environment core2foraws --target menuconfig_

"**Use the direction keys on your keyboard** to go to Component config –> Amazon Web Services IoT Platform and open AWS IoT Endpoint Hostname to set the string."

The direction keys do not work in a terminal within Visual Studio Code

You have to use the J/K keys:

see:

https://github.com/platformio/platform-espressif32/issues/423

**Comment by rashedtalukder** [comment]
What language do you have set for your keyboard?

**Comment by xian042** [comment]
Keyboard is "English (United States)" under  _Windows Settings > Time & Language > Language_

**Comment by rashedtalukder** [comment]
Fixed regression from https://github.com/m5stack/Core2-for-AWS-IoT-EduKit/issues/56
