### ISSUE TITLE
Screen is blank with small clicking noise. Unable to power on or restart after device has been configured

### ISSUE THREAD

**Issue by maulsparks** [m5stack/Core2-for-AWS-IoT-EduKit#65]
Initially, after charging the device was configured the device stayed inactive for several weeks (about 4) and upon reconnecting to the laptop, a blank screen and a small clicking noise can be heard. Unable to power on or restart the device. Any ideas on how to proceed or fix?

**Comment by rashedtalukder** [comment]
This if normal behavior when you don’t have an application loaded in your device after erasing as noted in here: https://edukit.workshop.aws/en/getting-started/run-rainmaker.html#erasing-the-firmware-with-platformio . So the device just reboots over and over causing the speaker amplifier to power cycle on and off repeatedly. To have it stop doing that, you just need to upload one of the provided projects like in here: https://edukit.workshop.aws/en/getting-started/run-rainmaker.html
