### ISSUE TITLE
Unclear how to find the device serial number

### ISSUE THREAD

**Issue by gherlein** [m5stack/Core2-for-AWS-IoT-EduKit#7]
Docs say "All are optional, but for fleet management it is recommended to fill the common name with the device serial. You can retrieve the device serial by monitoring the serial port while running the Core2-for-AWS-IoT-EduKit-Factory-Firmware application on your M5Stack Core2 for AWS IoT EduKit reference hardware."

These docs need to be a lot more clear and proscriptive.  Closest thing I could find is this

psram: This chip is ESP32-D0WD␛[0m

Docs should CLEARLY call out how to find the serial number.  Better, a tool to extract that would be nice

**Comment by rashedtalukder** [comment]
Updated the note with greater clarity and instructions how to retrieve it:
https://edukit.workshop.aws/en/blinky-hello-world/device-provisioning.html#generating-a-device-certificate-manifest
