### ISSUE TITLE
The default AWS IoT Policy allows Client ID spoofing

### ISSUE THREAD

**Issue by debug-ito** [m5stack/Core2-for-AWS-IoT-EduKit#81]
The `registration_helper.py` in the Blinky-Hello-World example creates a AWS IoT Policy (named "Default") like the following.

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "iot:Connect"
      ],
      "Resource": [
        "arn:aws:iot:*:*:client/${iot:ClientId}"
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
        "iot:Publish",
        "iot:Receive"
      ],
      "Resource": [
        "arn:aws:iot:*:*:topic/${iot:ClientId}/*",
        "arn:aws:iot:*:*:topic/$aws/things/${iot:ClientId}/shadow/*"
      ]
    },
  (snip)
}
```

This policy is insecure. This policy allows a client to use **ANY** client ID. As a result, a device can publish messages impersonating other devices, and it can eavesdrop messages for other devices.

See also: https://docs.aws.amazon.com/iot/latest/developerguide/security-best-practices.html#secure-mqtt

Although I didn't test it, a solution would be to use `${iot:Connection.Thing.ThingName}` for the resource to allow `iot:Connect` action, as described in the above link. The Thing Name is bound to the client certificate, so it would force a device to use its own client ID only.

**Comment by rashedtalukder** [comment]
Hi @debug-ito, you are right about using the client Id being bad, we don't do that. You can see the policy that's generated by the script [here](https://github.com/m5stack/Core2-for-AWS-IoT-EduKit/blob/753e36ff130ffa4be9ee4bf0cdc490ee84fbc331/Blinky-Hello-World/utilities/trustplatform/TrustnGO/Microchip_manifest_handler.py#L16-L56). It could be that you already had a policy named "Default" with the bad policy. Our script does not overwrite existing policies, things, or certificates.

**Comment by rashedtalukder** [comment]
@debug-ito, thank you for reporting and filing this. I've updated the policy document and given the policy a more unique name.

**Comment by debug-ito** [comment]
Thanks!
