### ISSUE TITLE
M5Stack Core2 ESP32 Development EduKit Factory Reset

### ISSUE THREAD

**Issue by kayesokua** [m5stack/Core2-for-AWS-IoT-EduKit#88]
Hi, I'm just getting started but this basic command doesn't work for me. `pio run --environment core2foraws --target upload`

Error that appears is "TypeError: 'module' object is not callable" even though pio is already installed through pip.

How do i proceed? I want to factory reset my m5stack edukit but I am stuck at this step.

**Comment by rashedtalukder** [comment]
Appears to be an error with PlatformIO. Here are some suggestions:
1) Reboot your computer
2) Delete the platformio directory:
-Windows: `C:\Users\{username}\.platformio\`
-Linux/Mac: `~/.platformio`
3) Delete the hidden `.pio` folder in your project folder.
4) Re-run `pio run --environment core2foraws --target upload`
